import type { IconName } from "@/components/ui/Icon";
import type { ToolId } from "@/lib/types";

export type ToolCategory =
  | "All Tools"
  | "Popular"
  | "Photo & Image"
  | "File Converter";

export interface ToolDef {
  id: ToolId;
  label: string;
  category: ToolCategory;
  isPopular?: boolean;
  status: "READY" | "BETA" | "SOON";
  key?: string;
  icon: IconName;
  version: 1 | 2;
  blurb: string;
}

export const CATEGORIES: ToolCategory[] = [
  "All Tools",
  "Popular",
  "Photo & Image",
  "File Converter",
];

export const TOOLS: ToolDef[] = [
  {
    id: "bgremove",
    label: "Background Remover",
    category: "Photo & Image",
    isPopular: true,
    status: "READY",
    key: "B",
    icon: "bgremove",
    version: 1,
    blurb: "Erase image backgrounds instantly. Click to key out matching colors, or use manual eraser.",
  },
  {
    id: "resize",
    label: "Image Resizer",
    category: "Photo & Image",
    isPopular: true,
    status: "READY",
    key: "R",
    icon: "resize",
    version: 1,
    blurb: "Resize images to precise dimensions using Canvas with aspect ratio locking.",
  },
  {
    id: "compress",
    label: "Image Compressor",
    category: "Photo & Image",
    isPopular: true,
    status: "READY",
    key: "K",
    icon: "compress",
    version: 1,
    blurb: "Reduce image file sizes with real-time quality scaling and WebP/JPG output.",
  },
  {
    id: "crop",
    label: "Crop & Rotate Tool",
    category: "Photo & Image",
    status: "READY",
    key: "C",
    icon: "crop",
    version: 1,
    blurb: "Crop or rotate photos to standard ratios or freehand selection handles.",
  },
  {
    id: "enhance",
    label: "AI Image Enhancer",
    category: "Photo & Image",
    status: "READY",
    key: "H",
    icon: "enhance",
    version: 2,
    blurb: "Enhance details using local contrast, sharpness boost, and auto color balancing.",
  },
  {
    id: "watermark",
    label: "Watermark Tool",
    category: "Photo & Image",
    status: "READY",
    key: "W",
    icon: "watermark",
    version: 1,
    blurb: "Add text or logo watermarks overlay onto photos with custom position and opacity.",
  },

  {
    id: "object",
    label: "Object Remover",
    category: "Photo & Image",
    status: "READY",
    key: "O",
    icon: "object",
    version: 2,
    blurb: "Brush over distractions and remove unwanted objects from your images seamlessly.",
  },
  {
    id: "filters",
    label: "Photo Filters",
    category: "Photo & Image",
    status: "READY",
    key: "F",
    icon: "filters",
    version: 2,
    blurb: "Apply curated aesthetic looks — mono, warm tone, vintage, vivid, and film presets.",
  },
  {
    id: "convert",
    label: "Format Converter",
    category: "File Converter",
    isPopular: true,
    status: "READY",
    key: "T",
    icon: "convert",
    version: 1,
    blurb: "Convert images between PNG, JPG, and WebP instantly inside your browser.",
  },
  {
    id: "jpg-to-png",
    label: "JPG to PNG Converter",
    category: "File Converter",
    isPopular: true,
    status: "READY",
    key: "1",
    icon: "convert",
    version: 1,
    blurb: "Turn JPG and JPEG images into PNG files for cleaner browser-safe output.",
  },
  {
    id: "png-to-jpg",
    label: "PNG to JPG Converter",
    category: "File Converter",
    isPopular: true,
    status: "READY",
    key: "2",
    icon: "convert",
    version: 1,
    blurb: "Convert PNG files to JPG with a white background and adjustable quality.",
  },
  {
    id: "webp-to-png",
    label: "WebP to PNG Converter",
    category: "File Converter",
    status: "READY",
    key: "3",
    icon: "convert",
    version: 1,
    blurb: "Export WebP images as PNG files for editing apps and older workflows.",
  },
  {
    id: "png-to-webp",
    label: "PNG to WebP Converter",
    category: "File Converter",
    status: "READY",
    key: "4",
    icon: "convert",
    version: 1,
    blurb: "Create compact WebP files from PNG images directly in your browser.",
  },
  {
    id: "svg-to-png",
    label: "SVG to PNG Converter",
    category: "File Converter",
    status: "READY",
    key: "5",
    icon: "convert",
    version: 1,
    blurb: "Rasterize SVG artwork into PNG files without uploading the vector source.",
  },
  {
    id: "svg-to-jpg",
    label: "SVG to JPG Converter",
    category: "File Converter",
    status: "READY",
    key: "6",
    icon: "convert",
    version: 1,
    blurb: "Convert SVG graphics to JPG with a neutral white canvas background.",
  },
  {
    id: "pdf-to-word",
    label: "PDF to Word Converter",
    category: "File Converter",
    isPopular: true,
    status: "READY",
    key: "7",
    icon: "convert",
    version: 2,
    blurb: "Extract readable PDF text into a downloadable DOCX document locally.",
  },
  {
    id: "word-to-pdf",
    label: "Word to PDF Converter",
    category: "File Converter",
    isPopular: true,
    status: "READY",
    key: "8",
    icon: "convert",
    version: 2,
    blurb: "Convert DOCX document text into a clean PDF file in your browser.",
  },
  {
    id: "txt-to-pdf",
    label: "TXT to PDF Converter",
    category: "File Converter",
    status: "READY",
    key: "9",
    icon: "convert",
    version: 2,
    blurb: "Turn plain text notes into a clean downloadable PDF document locally.",
  },
  {
    id: "txt-to-word",
    label: "TXT to Word Converter",
    category: "File Converter",
    status: "READY",
    key: "0",
    icon: "convert",
    version: 2,
    blurb: "Convert TXT files into editable DOCX documents without uploading them.",
  },
  {
    id: "markdown-to-html",
    label: "Markdown to HTML Converter",
    category: "File Converter",
    status: "READY",
    icon: "convert",
    version: 2,
    blurb: "Convert Markdown notes into a standalone HTML file in your browser.",
  },
  {
    id: "html-to-pdf",
    label: "HTML to PDF Converter",
    category: "File Converter",
    status: "READY",
    icon: "convert",
    version: 2,
    blurb: "Extract readable HTML page text into a simple PDF document locally.",
  },
  {
    id: "json-to-csv",
    label: "JSON to CSV Converter",
    category: "File Converter",
    status: "READY",
    icon: "convert",
    version: 2,
    blurb: "Flatten arrays of JSON objects into spreadsheet-friendly CSV files.",
  },
  {
    id: "csv-to-json",
    label: "CSV to JSON Converter",
    category: "File Converter",
    status: "READY",
    icon: "convert",
    version: 2,
    blurb: "Convert CSV tables into formatted JSON arrays for apps and APIs.",
  },
  {
    id: "adjust",
    label: "Color Adjustments",
    category: "Photo & Image",
    status: "READY",
    key: "A",
    icon: "adjust",
    version: 1,
    blurb: "Fine-tune brightness, contrast, saturation, temperature, and exposure live.",
  },
  {
    id: "collage",
    label: "Collage Maker & Photo Grid",
    category: "Photo & Image",
    isPopular: true,
    status: "READY",
    key: "G",
    icon: "collage",
    version: 1,
    blurb: "Combine multiple photos into grid layouts (2x2, 3x3, side-by-side, split) with custom spacing & borders.",
  },
];

export const TOOL_BY_ID: Record<ToolId, ToolDef> = Object.fromEntries(
  TOOLS.map((t) => [t.id, t]),
) as Record<ToolId, ToolDef>;
